### ISSUE TITLE
from_dict in AdmnisitrativeFee causes AssertionError for None Values

### ISSUE THREAD

**Issue by gebauerm** [Transparency-Information-Language/python-tilt#2]
I want to report a Bug for the Class of Administrative Fee.
When I want to initiate AdministatriveFee via `from_dict` I get an AssertionError.
The Error is caused by not accounting for `None` Entries in the input data. When `from_float` is called on a `None` Value within the Class it can not initiate an AdministrativeFee Object.

## To Reproduce
Input_Data:
`{'amount': None, 'currency': None}`

Respective Class:
```
class AdministrativeFee:
    """The fee that refers to several copies."""
    """The amount of money to be paid for a copy."""
    amount: float
    """The currency in which the amount of money for one copy has to be provided acc. to ISO
    4217.
    """
    currency: str

    def __init__(self, amount: float, currency: str) -> None:
        self.amount = amount
        self.currency = currency

    @staticmethod
    def from_dict(obj: Any) -> 'AdministrativeFee':
        assert isinstance(obj, dict)
        amount = from_float(obj.get("amount"))
        currency = from_str(obj.get("currency"))
        return AdministrativeFee(amount, currency)

    def to_dict(self) -> dict:
        result: dict = {}
        result["amount"] = to_float(self.amount)
        result["currency"] = from_str(self.currency)
        return result
```

Code:
```
input_data = {'amount': None, 'currency': None}
fee = AdministrativeFee.from_dict(input_data)
```

Output:

```
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/home/gebauer/Desktop/repo/chatbot/.venv/lib/python3.7/site-packages/tilt/tilt.py", line 87, in from_dict
    amount = from_float(obj.get("amount"))
  File "/home/gebauer/Desktop/repo/chatbot/.venv/lib/python3.7/site-packages/tilt/tilt.py", line 18, in from_float
    assert isinstance(x, (float, int)) and not isinstance(x, bool)
AssertionError
```

**Comment by eliasgruenewald** [comment]
`{'amount': None, 'currency': None}` is not a valid input, it should be `{'amount': 0, 'currency': 'EUR'}`…

(of course, error handling is missing here, but this applies to all fields, right? almost the complete library is generated code, which is why I don't necessarily want to change this here).

**Comment by gebauerm** [comment]
Okay I get it. 
Would apply to all fields with none values, yes.
